version: "3"
services:
  cuentas-banco-app:
    #container_name: banco-app
    image: cuentas-banco-app
    restart: always
    build: . 
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./db:/var/lib/mysql	
    ports:
     - 3307:3306
    environment:
      MYSQL_DATABASE: banco
      MYSQL_ROOT_PASSWORD: root
      